import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/providers/theme-provider";
import { Anek_Devanagari } from "next/font/google";

const fontAnek = Anek_Devanagari({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600"],
  variable: "--font-anek",
});

export const metadata: Metadata = {
  title: "Dealo Care",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontAnek.className}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
